version: '3'
services:
  database:
    container_name: NS_Database
    image: postgres:9.6
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: "exit 0"
    ports:
      - 5432:5432

    restart: unless-stopped

  pgadmin:
    container_name: NS_Database_GUI
#    image: dpage/pgadmin4:5.7
    image: biarms/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-teunis@teunis.dev}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
        - pgadmin:/root/.pgadmin
    depends_on:
      database:
        condition: service_healthy
    ports:
      #- 5050:80
      - 5050:5050


  site:
    container_name: NS_Site
    environment:
      PYTHONBUFFERED: 0
    image: dockerteun/ns:latest
    privileged: true
    ports:
      - 8085:8085
    restart: unless-stopped



volumes:
  database-data:
  pgadmin:


