
name: NS-stackbuilder
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  buildx:
    name: builx build & push image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Site/Dockerfile
          platforms: linux/arm/v6,linux/arm/v7,linux/amd64
          push: true
          tags: |
            dockerteun/ns:latest
            dockerteun/ns:${{ github.run_number }}
    

      -
        name: trigger single Job
        uses: appleboy/jenkins-action@master
        with:
          url: "http://jenkins.teunisdev.nl"
          user: "Teunis"
          token: ${{ secrets.JENKINS_TOKEN }}
          job: "NS-Docker-Deploy"
 
